<html>
    <head>
        <link href="/css/bootstrap.min.css" rel="stylesheet" >
        <script src="/js/bootstrap.bundle.min.js" ></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    </head>
    <div class="container mb-4">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">SimpleStock</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link active" aria-current="page" href="/home">Home</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" 
        id="navbarDropdownMenuLink" 
        data-bs-toggle="dropdown" 
        aria-haspopup="true" 
        aria-expanded="false">
          Products
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="/product">Product index</a>
            <a class="dropdown-item" href="/product/create">Product creation</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" 
        id="navbarDropdownMenuLink2" 
        data-bs-toggle="dropdown" 
        aria-haspopup="true" 
        aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink2">
            <a class="dropdown-item" href="/category">Category index</a>
            <a class="dropdown-item" href="/category/create">Category creation</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" 
        id="navbarDropdownMenuLink2" 
        data-bs-toggle="dropdown" 
        aria-haspopup="true" 
        aria-expanded="false">
          Units
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink2">
            <a class="dropdown-item" href="/unit">Unit index</a>
            <a class="dropdown-item" href="/unit/create">Unit creation</a>
        </div>
      </li>
    </ul>
  </div>
</nav>
    </div>
    <div class="container">
    <?=$yield?>
    </div>
</html>