<?php if(isset($message)):?>
    <div aria-live="polite" aria-atomic="true" class="bg-dark position-relative bd-example-toasts">
        <div class="toast-container position-absolute p-3 end-0" id="toastPlacement">
            <div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="toast-header">
                    Notification
                    <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                </div>
                <div class="toast-body">
                    <div class="alert alert-<?=isset($error)?'danger':'success'?>" role="alert">
                        <?=$message?>
                        <?php if(isset($error)): ?> <i class="bi bi-x-circle"></i> 
                        <?php else: ?> <i class="bi bi-check-circle"></i> 
                        <?php endif?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        let t = new bootstrap.Toast(document.getElementsByClassName('toast')[0]);
        t.show();
    </script>

<?php endif;?>
