<?php /** @layout layouts.main */ ?>
<div class="row mb-2">
    <div class="col">    
        <?php if(isset($id) && $id): ?>
            <h2><i class="bi bi-box-seam"></i> Category <?=$category?> (<?=$id?>)</h2>
        <?php else: ?>
            <h2><i class="bi bi-box-seam"></i> Create category</h2>
        <?php endif ?>
    </div>
</div>
<div class="row">
    <div class="col-6">   
        <form method="POST" action="/category/store">
            <?=  isset($id) ? '<input type="hidden" name="id" value="'.$id.'">' : '' ?> 
            <div class="mb-3 col">
                <label for="category" class="form-label">Category name</label>
                <input type="text" class="form-control" id="category" name="category" placeholder="e.g. Cold drinks" value="<?=$category?>">
            </div>           
            <button type="submit" class="btn btn-primary"><i class="bi bi-box-seam"></i> <?=isset($id)?'Update':'Save'?> category</button>
            <a href="/category" class="btn btn-warning"><i class="bi bi-house-door"></i>Back to index</a>
        </form>
    </div>
</div>