
<div class="row mb-2">
    <div class="col">    
        <?php if(isset($id) && $id): ?>
            <h2><i class="bi bi-box-seam"></i> Product <?=$name?> (<?=$id?>) detail</h2>
        <?php else: ?>
            <h2><i class="bi bi-box-seam"></i> Create product</h2>
        <?php endif ?>
    </div>
</div>

<div class="row">
    <div class="col-6">   
        <?php if(isset($id) && $id): ?>
        <h3>Basic details</h3>   
        <?php endif ?>
        <form method="POST" action="/product/store">
            <?=  isset($id) ? '<input type="hidden" name="id" value="'.$id.'">' : '' ?> 
            <div class="mb-3 col">
                <label for="name" class="form-label">Product name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="e.g. Keptchup" value="<?=$name?>">
            </div>
            <div class="mb-3 col">
                <label for="name" class="form-label">Product presentation</label>
                <input type="text" class="form-control" id="presentation" name="presentation" placeholder="e.g. 1 Bottle" value="<?=$presentation?>">
            </div>
            <div class="mb-3 col">
                <label for="unit" class="form-label">Unit</label>
                <select name="unit" id="unit" class="form-select">
                    <?php foreach($units as $un):?>
                        <option <?= $unit == $un['unit'] ? 'selected' : ''; ?>><?=$un['unit'];?></option>
                    <?php endforeach; ?>
                    <option>Other</option>
                </select>
            </div>
            <div class="mb-3 col">
                <label for="category" class="form-label">Category</label>
                <select name="category" id="category" class="form-select">
                    <?php foreach($categories as $cat):?>
                        <option <?= $category == $cat['category'] ? 'selected' : ''; ?>><?=ucwords($cat['category']);?></option>
                    <?php endforeach; ?>
                    <option>Other</option>
                </select>
            </div>
            <?php if(!isset($id)):?>
                <div class="mb-3 col">
                    <label for="initialStock" class="form-label">Initial stock</label>
                    <input type="number" step="0.1" class="form-control" id="initialStock" name="initialStock" placeholder="e.g. 100.00" value="0">
                </div>   
            <?php endif;?>            
            <button type="submit" class="btn btn-primary"><i class="bi bi-box-seam"></i> <?=isset($id)?'Update':'Save'?> product</button>
            <a href="/product" class="btn btn-warning"><i class="bi bi-house-door"></i>Back to index</a>
        </form>



    </div>
    <?php if(isset($id)):?>
    <div class="col-6">
        <h3>Adjust current stock (<?=$stock.' '.$unit?>) </h3>
        
        <form class="" method="POST" action="/stock/adjust">
            <?=  isset($id) ? '<input type="hidden" name="product_id" value="'.$id.'">' : '' ?> 
            <div class="mb-3 col form-fieldset">
                <label for="AdjustmentTypes" class="form-label">Adjustment type</label>
                <div id="AdjustmentTypes">
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="transactionType" id="inlineRadio1" value="add" checked>
                        <label class="form-check-label" for="inlineRadio1">Add to stock</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="transactionType" id="inlineRadio2" value="substract">
                        <label class="form-check-label" for="inlineRadio2">Sustract from stock</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="transactionType" id="inlineRadio3" value="set">
                        <label class="form-check-label" for="inlineRadio3">Set current stock</label>
                    </div>
                </div>
            </div>
            
            <div class="mb-3 col">
                <label for="amount" class="form-label">Amount</label>
                <input type="number" min="0" step="0.01" class="form-control" id="amount" name="amount" placeholder="e.g. 100.00" value="">
            </div>   
            <div class="mb-3 col">
                <label for="observation" class="form-label">Observation</label>
                <input type="text"  class="form-control" id="observation" name="observation" placeholder="e.g. Stock adjusment" value="">
            </div>
            <button type="submit" class="btn btn-primary"><i class="bi bi-stack"></i> Update stock</button>
        </form>
    </div>
    <?php endif;?>
</div>