
<div class="row mb-2">
    <div class="col">    
        <?php if(isset($id) && $id): ?>
            <h2><i class="bi bi-box-seam"></i> Product <?=$name?> (<?=$id?>) detail</h2>
        <?php else: ?>
            <h2><i class="bi bi-box-seam"></i> Create product</h2>
        <?php endif ?>
    </div>
</div>

<div class="row">
    <div class="col">
        <?=$message?>

        <form method="POST" action="/product/store">
            <?=  isset($id) ? '<input type="hidden" name="id" value="'.$id.'">' : '' ?> 
            <div class="mb-3 col-4">
                <label for="name" class="form-label">Product name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="e.g. Kepthup" value="<?=$name?>">
            </div>
            <div class="mb-3 col-4">
                <label for="name" class="form-label">Product presentation</label>
                <input type="text" class="form-control" id="presentation" name="presentation" placeholder="e.g. 1 Bottle" value="<?=$presentation?>">
            </div>
            <div class="mb-3 col-4">
                <label for="unit" class="form-label">Unit</label>
                <select name="unit" id="unit" class="form-select">
                    <?php foreach($units as $un):?>
                        <option <?= $unit == $un['unit'] ? 'selected' : ''; ?>><?=$un['unit'];?></option>
                    <?php endforeach; ?>
                    <option>Other</option>
                </select>
            </div>
            <div class="mb-3 col-4">
                <label for="category" class="form-label">Category</label>
                <select name="category" id="category" class="form-select">
                    <?php foreach($categories as $cat):?>
                        <option <?= $category == $cat['category'] ? 'selected' : ''; ?>><?=$cat['category'];?></option>
                    <?php endforeach; ?>
                    <option>Other</option>
                </select>
            </div>
            <?php if(!isset($id)):?>
                <div class="mb-3 col-4">
                    <label for="initialStock" class="form-label">Initial stock</label>
                    <input type="text" class="form-control" id="initialStock" name="initialStock" placeholder="e.g. 100.00" value="0">
                </div>   
            <?php endif;?>            
            <button type="submit" class="btn btn-primary"><i class="bi bi-box-seam"></i> <?=isset($id)?'Update':'Create'?> product</button>
            <a href="/product" class="btn btn-warning"><i class="bi bi-house-door"></i>Back to index</a>
        </form>



    </div>
</div>