<?=$message?>
<?php if(isset($id) && $id): ?>
<h2>Product <?=$name?> (<?=$id?>) detail</h2>
<?php else: ?>
    Product creation
<?php endif;?>
<form method="POST" action="/product/store">
    <?=  isset($id) ? '<input type="hidden" name="id" value="'.$id.'">' : '' ?>
    <label for="name">Name</label> <input name="name" value="<?=$name?>"><br>
    <label for="presentation">Presentation</label> <input name="presentation" value="<?=$presentation?>"><br>
    <label for="unit">Unit</label>
    <select name="unit">
        <?php foreach($units as $un):?>
            <option <?= $unit == $un['unit'] ? 'selected' : ''; ?>><?=$un['unit'];?></option>
        <?php endforeach; ?>
        <option>Other</option>
    </select><br>
    <label for="category">Category</label>
    <select name="category">
        <?php foreach($categories as $cat):?>
            <option <?= $category == $cat['category'] ? 'selected' : ''; ?>><?=$cat['category'];?></option>
        <?php endforeach; ?>
        <option>Other</option>
    </select><br>
    <label for="stock">Stock</label> <input name="stock" value="<?=$stock?>"><br>
    <button type="submit">Save product</button>
</form>
<br>
<a href="/product">Back to index</a>