
<div class="row">
    <div class="col">
        <h2>Product Index</h2>
    </div>
</div>

<div class="row">
    <div class="col">
        <table class="table">
            <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Presentation</th>
                <th scope="col">Unit</th>
                <th scope="col">Category</th>
                <th scope="col">Stock</th>
                <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
            <?php
                //$products = (object)$products;
                foreach ($products as $id => $product) {
                extract($product);
                ?>
                <tr>
                    <th scope="row"><?=$id?></th>
                    <td><a href="/product/<?=$id?>"><?=$name?></a></td>
                    <td><?=$presentation?></td>
                    <td><?=$unit?></td>
                    <td><?=$category?></td>
                    <td><?=$stock?></td>
                    <td>
                        <a class="btn btn-primary btn-sm" href="/product/edit/<?=$id?>"><i class="bi bi-pencil-square"></i>Edit</a>
                        <form method="POST" action="/product/delete/<?=$id?>">
                            <button class="btn btn-danger btn-sm" type="submit"><i class="bi bi-trash"></i>Delete</button>
                        </form>
                    </td>
                </tr>
                <?php
                }
                ?>
            </tbody>
        </table>    
    </div>
</div>