
<div class="row mb-2">
    <div class="col">
        <h2><i class="bi bi-list-check"></i> Product Index</h2>
    </div>
</div>
<?php slot('layouts/message',['message'=>request('message'), 'error' => request('error')]); ?>
<div class="row">
    <div class="col-4">
        <a class="btn btn-primary" href="/product/create"><i class="bi bi-box-seam"></i> Create product</a>
    </div>
    <div class="col-12">        
        <table class="table">
            <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Category</th>
                <th scope="col">Presentation</th>                
                <th scope="col">Stock</th>
                <th scope="col">Unit</th>
                <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
            <?php
                //$products = (object)$products;
                foreach ($products as $id => $product) {
                extract($product);
                ?>
                <tr>
                    <th scope="row"><?=$id?></th>
                    <td><a href="/product/<?=$id?>"><?=$name?></a></td>
                    <td><?=$category?></td>
                    <td><?=ucwords($presentation)?></td>
                    <td><?=$stock?></td>
                    <td><?=$unit?></td>
                    <td>
                        <form method="POST" action="/product/delete/<?=$id?>" class="m-0">
                            <a class="btn btn-secondary btn-sm" href="/product/edit/<?=$id?>"><i class="bi bi-pencil-square"></i></a>
                            <button class="btn btn-danger btn-sm" type="submit"><i class="bi bi-trash"></i></button>
                        </form>
                    </td>
                </tr>
                <?php
                }
                ?>
            </tbody>
        </table>    
    </div>

</div>