<?php /** @layout layouts.main */ ?>
<?php extract($product); ?>
<div class="row mb-2">
    <div class="col">
        <h2><i class="bi bi-journal-text"></i> Product details</h2>
    </div>
</div>
<div class="row">
    <div class="col-sm-12 col-md-4">
        <div class="card" style="width: 18rem;">
            <img src="/img/product.png" class="card-img-top mx-auto d-block p-2" alt="Product <?=$name?>" style="max-width:150px">
            <div class="card-body">
                <h5 class="card-title"><?=$name?></h5>
                <h6 class="card-subtitle mb-2 text-muted">ID: <?=$id?></h6>
                <p class="card-text"></p>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><label for="presentation">Presentation:</label> <span><?=$presentation?></span></li>
                    <li class="list-group-item"><label for="unit">Unit:</label> <span><?=$unit?></span><br></li>
                    <li class="list-group-item"><label for="category">Category:</label> <span><?=ucwords($category)?></span></li>
                    <li class="list-group-item"><label for="stock">Stock:</label> <span><?=$stock?></span></li>
                </ul>

            </div>
            <div class="card-body">
            <a href="/product/edit/<?=$id?>" class="btn btn-primary btn-sm"><i class="bi bi-pencil-square"></i>Edit</a>
                <a href="/product" class="btn btn-warning btn-sm"><i class="bi bi-house-door"></i>Back to index</a>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-md-8">
        <h3>Stock transactions <small><a href="/product/edit/<?=$id?>" class="btn btn-primary btn-sm"><i class="bi bi-stack"></i>Update stock</a></small></h3>
        
        <div class="overflow-auto" style="max-height:400px;">
        <table class="table" >
            <thead>
                <tr>
                    <td>ID</td>
                    <td>Date</td>
                    <td>Amount</td>                   
                    <td>Balance</td>
                    <td>Observation</td>
                </tr>
            </thead>
            <tbody>
            <?php    
                foreach ($transactions as $id => $transaction):
                extract($transaction);
            ?>
                    <tr>
                        <td><?=$id?></td>
                        <td><?=$date?></td>
                        <td><?=$amount?></td>
                        <td><?=$stock?></td>
                        <td><?=$observation?></td>
                    </tr>
            <?php
                endforeach;
            ?>
            </tbody>

        </table>
        </div>
    </div>
</div>