<?php /** @layout layouts.main */ ?>
<div class="row mb-2">
    <div class="col">    
        <?php if(isset($id) && $id): ?>
            <h2><i class="bi bi-info-circle"></i> Unit <?=$unit?> (<?=$id?>)</h2>
        <?php else: ?>
            <h2><i class="bi bi-info-circle"></i> Create unit</h2>
        <?php endif ?>
    </div>
</div>
<?php include path(configdir('views'),'layouts','message.phtml'); ?>
<div class="row">
    <div class="col-6">   
        <form method="POST" action="/unit/store">
            <?=  isset($id) ? '<input type="hidden" name="id" value="'.$id.'">' : '' ?> 
            <div class="mb-3 col">
                <label for="unit" class="form-label">Unit name</label>
                <input type="text" class="form-control" id="unit" name="unit" placeholder="e.g. Kg" value="<?=$unit?>">
            </div>           
            <button type="submit" class="btn btn-primary"><i class="bi bi-info-circle"></i> <?=isset($id)?'Update':'Save'?> unit</button>
            <a href="/unit" class="btn btn-warning"><i class="bi bi-house-door"></i>Back to index</a>
        </form>
    </div>
</div>